name: Rust CI
on:
  push:
    branches:
      - main
    paths:
      - "native/**"
  pull_request:
    paths:
      - "native/**"
  workflow_dispatch:

jobs:
  lint_rust:
    name: Lint Rust
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        manifest:
          - native/nimblelz4/Cargo.toml

    steps:
      - name: Check out this repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
          override: true

      - name: Check if code is formatted
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=${{ matrix.manifest }} --all -- --check

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path=${{ matrix.manifest }} -- -Dwarnings
